# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GooeyTabbarSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GooeyTabbarSample
  pod 'EasyPeasy'
  pod 'PayWandBasicElements', :path => '../../PayWandBasicElements/'
  pod 'TtroGooeyTabbar', :path => '../'

  target 'GooeyTabbarSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GooeyTabbarSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
